PA1_template
Saravanan Subramaniam

Sunday, September 14, 2014

#Loading and preprocessing the Data
Dataset <- read.csv("C:/Users/Dr.Saravanan/Desktop/R/activity.csv")
Dataset$datetime <- as.POSIXct(
  with(
    Dataset,
    paste(
      date,
      paste(interval %/% 100, interval %% 100, sep=":"))
  ),
  format="%Y-%m-%d %H:%M",tz="")
require(ggplot2)
require(scales)
require(grid)

##What is mean total number of steps taken per day?

# Data for the histogram

Number_of_steps_perday <- setNames(
  aggregate(
    steps~as.Date(date),
    Dataset,
    sum,
    na.rm = TRUE),
  c("Date","Steps")
)
#Plotting the histogram

hist1<- ggplot(Number_of_steps_perday,aes(x=Date,y=Steps)) + 
  geom_bar(stat="identity") + 
  ggtitle("(Number of steps per day)")
print(hist1)

#Summary Number_of_steps_perday 

summary(Number_of_steps_perday$Steps)
Mean_Median1 <- c(mean = mean(stepsPerDay$steps),median = median(stepsPerDay$steps))
print(Mean_Median)

## What is the average daily activity pattern?

#Average daily pattern: Average distribution of steps per day by intervals.

Ave_Pattern <- aggregate(steps~interval,activity,mean,na.rm = TRUE)
Ave_Pattern$time <- as.POSIXct(with(Ave_Pattern,paste(interval %/% 100, interval %% 100, sep=":")),format="%H:%M")
plot <- ggplot(Ave_Pattern,aes(x=time,y=steps))  + 
  scale_x_datetime(breaks = date_breaks("2 hour"),labels = date_format("%H:%M"))
print(plot)

#Imputing Missing Values

Missing_Values <- aggregate(cnt~date,cbind(Dataset[is.na(Dataset$steps),],cnt=c(1)),sum,na.rm = FALSE)
Missing_Values$dow <- weekdays(as.Date(Missing_Values$date),abbreviate=TRUE)
print(Missing_Values[,c(1,3,2)])
unique(Missing_Values$dow)

# filling missing values 

Reference <- aggregate(steps~interval+weekdays(datetime,abbreviate=TRUE),Dataset,FUN=mean,na.rm=TRUE)
colnames(Reference) <- c("interval","dow","Avg_steps")
Reference$dow <- factor(Reference$dow,levels = c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"))

ggplot(Reference,aes(x=interval,y=Avg_steps)) + geom_line() + facet_grid("dow ~ .")

# Fixed data set

Dataset$dow <- weekdays(Dataset$datetime,abbreviate=TRUE)
af <- merge(Dataset,ref_ds,by=c("dow","interval"),all.x = TRUE)
af <- af[with(af,order(date,interval)),]
af$fixed_steps <- ifelse(is.na(af$steps),af$avg_steps,af$steps)

# calculating data set for histogram

Number_of_steps_perday1 <- setNames(
  aggregate(
    fixed_steps~as.Date(date),
    af,
    sum,
    na.rm = TRUE),
  c("date","steps")
)
# plotting histogram

hist2 <- ggplot(Number_of_steps_perday1,aes(x=date,y=steps)) + 
  geom_bar(stat="identity") + 
  ggtitle("Total number of steps per day (fixed data)")
Mean_Median2 <- c(mean = mean(stepsPerDay2$steps),median = median(stepsPerDay2$steps))
comparison <- rbind(source = mm_1, fixed = mm_2, delta = mm_2-mm_1)
print(comparison)

#Are there differences in activity patterns between weekdays and weekends?

# Differneces in patterns for working days and weekends.

week_diff <- aggregate(
  steps~dow+interval,  # group steps by weekend/weekday and interval to find average steps 
  with(
    Dataset,
    data.frame(
      dow = factor(
        ifelse(
          weekdays(as.Date(date)) %in% c("Sunday","Saturday"),
          "weekend",  # if sunday or saturday
          "weekday"   # else
        )
      ),
      interval,
      steps
    )
  ),
  FUN = mean,
  rm.na = TRUE
)
# Plotting the result
ggplot(week_diff,aes(x=interval,y=steps)) + geom_line() + facet_grid("dow ~ .")
